services:

  web:
    image: nginx:latest
    container_name: pizza-city_nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
      - db

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: pizza-city_php
    volumes:
      - ./:/var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: pizza-city_db
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3316:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=students
      - REDIS_HOST=cache
      - REDIS_PORT=6379

  phpmyadmin:
    image: phpmyadmin
    container_name: pizza-city_phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

  node:
    image: node:latest
    container_name: pizza-city_node
    ports:
        - "3000:3000"
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true

  cache:
    image: redis:latest
    container_name: pizza-city_redis
